---
driver:
  name: vagrant

provisioner:
  name: puppet_apply
  manifests_path: spec/manifests
  modules_path: .kitchen-modules
  require_chef_for_busser: false
  resolve_with_librarian_puppet: false
  puppet_debug: <%= ENV['PUPPET_DEBUG'] %>
  custom_options: <%= ENV['PUPPET_COLOR'] %>
  require_puppet_collections: true
  puppet_detailed_exitcodes: true
  max_retries: 3
  retry_on_exit_code:
    - 1
    - 2
    - 4
    - 6

transport:
  name: winrm

platforms:
  - name: windows-2012r2
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2012r2
  - name: windows-2019-core
    driver_plugin: vagrant
    driver_config:
      box: red-gate/windows-2019-core

verifier:
  name: shell

suites:
  - name: default
    provisioner:
      manifest: default.pp
    verifier:
      command: rspec -c -f d -I spec spec/acceptance/default_spec.rb
